### ISSUE TITLE
Integrate GraphiQL UI

### ISSUE THREAD

**Issue by JamieMeyer** [lukemurray/EntityGraphQL#10]
GraphiQL would be a great addition to this project, and would help to provide a more well-rounded demo. It will also demonstrate several areas where the demo app has fallen out of sync with the evolving work being done on new functionality.

**Comment by lukemurray** [comment]
These is partially there in master. Not currently supported in the introspection query. But you can use it and query the demo data.

**Comment by lukemurray** [comment]
For the the demo. GraphiQL is in master (obviously not included in releases). Track #7 for when the introspection query works. And feel free to submit PRs to make a better data model for demo.
