### ISSUE TITLE
Filtering with id doesn't work

### ISSUE THREAD

**Issue by TheHunter** [lukemurray/EntityGraphQL#11]
Hi all,
the default schema generates a not plurar property (as mentioned in the example), but when It tries to filter  result with id parameter I get this result:

message": "Constructor on type 'EntityGraphQL.Schema.RequiredField`1[[System.UInt32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' not found."
}

my query is:
{property(id : 1) { id name type location { id } }}

What's the problem?, after that the example is not updated (It seems).

Thanks a lot.

**Comment by lukemurray** [comment]
Thanks for that. it was because the value `1` is interpreted as an `int` not a `uint`. Fix coming in 0.15.1
