### ISSUE TITLE
EQL syntax doesn't work

### ISSUE THREAD

**Issue by TheHunter** [lukemurray/EntityGraphQL#12]
Hi all,
the EQL statement mentioned as an example, doesn't work, and the error is related to boolean condition.

(type.id = 2 or type.id = 3) and type.name == "Farm"

Could you please check the statement ?

Thanks a lot.

**Comment by lukemurray** [comment]
This should be `(type.id = 2 or type.id = 3) and type.name = "Farm"`. I just updated the Readme, thanks.

Note the single `=` instead of the double `==`. This is because in EQL there is no assignment so I used the single `=` for "equals". Given the audience that might have to be revised.

**Comment by TheHunter** [comment]
Hi All,
sorry but It doesn't work yet.

Do I open a new issue for this error ?

However, may thing doesn't work, for example:

- Not equals, It's not exposed any example.. I've tried with "!=", "!==",  "<>", but nothing
- Or, And condition doesn't work

So is It possible to understand these errors ?

**Comment by lukemurray** [comment]
Do you have a more detailed example of how you're trying to use this?

**Comment by TheHunter** [comment]
Consider my model (more less identical the yours)

![image](https://user-images.githubusercontent.com/992665/66392085-2b91fa80-e9cf-11e9-8182-cab422c856c2.png)

// and, the value of request.Query is "(type.id = 1 or type.id = 2)", like your example

![image](https://user-images.githubusercontent.com/992665/66392496-4b75ee00-e9d0-11e9-9cf6-581e0fe1a07e.png)

If you try OrElse as indicated in the exception message, it's consider the first part of query, so "(type.id = 1".

you can reproduce this error with a simple Unit Test.

**Comment by lukemurray** [comment]
Sorry, this is an issue with how the parser takes the order of the operators (here being `=, `or` and `=`). 

You can fix this now with explicitly defining your order with brackets like you would else where. So the query becomes `(type.id = 1) or (type.id = 2)`

I updated the Readme, I'll look at another time on making the operators order better/smarter

**Comment by TheHunter** [comment]
Hi,
like that works, but I have another questions.. How does it work for the others operators ?
example: 
- (type.id != 1) 
- usage of linq methods (where(), order(), take(), skip())

The ideal would be to do an example which you have a complex query criteria, with a projection of data... maybe following the same Data model expose in the **Readme**.

Thanks
