### ISSUE TITLE
Compile result doesn't contain Expression property.

### ISSUE THREAD

**Issue by TheHunter** [lukemurray/EntityGraphQL#13]
Hi all,
in the example present in this documentation doesn't compile, because property Expression doesn't exists, instead LambdaExpression exists.

Could you verify the documentation ?

// we create a schema provider to compile the statement against our Property type
var schemaProvider = SchemaBuilder.FromObject<Property>();
var compiledResult = EqlCompiler.Compile(myConfigurationEqlStatement, schemaProvider);
// you get your list of Properties from you DB
var thingsToShow = myProperties.Where(compiledResult.Expression);

Thanks a lot.

**Comment by lukemurray** [comment]
Yes, you are correct. It should be `LambdaExpression` e.g. `var thingsToShow = myProperties.Where(compiledResult.LambdaExpression);`.

Updated readme.

Thanks again.
