### ISSUE TITLE
Queries for Primary or Composite Keys

### ISSUE THREAD

**Issue by JTravis76** [lukemurray/EntityGraphQL#14]
This is one of the nicest implementation in C# I've played with so far. Really Like how you already include the EF entities models. Other solutions want to re-add them. Felt like I was duplicating the work.

Do have a question when querying against primary or composite keys.

Not able to query when the primary key is not "**id**". Updated the schema from GroupId to Id and it worked perfectly.
`{ group(groupid:1){ name } }`

> "message": "Error compiling query 'group(id:1)'. Field group not found"

This also goes for composite keys. GroupMembers have keys for username and groupid
`{ groupmembers { username, email, groupid } }`

>  "message": "Exception has been thrown by the target of an invocation."

It appears you are building a Lambda Expression, but not able to tell how you where calling EF.
Is this a Where() statement or using a Find() option against the keys?

BTW, been working on getting GraphiQl UI to work. Making some headway, building the schema model for the Document Explorer causing some heartburn,

**Comment by lukemurray** [comment]
Thanks!

I'm away from computer today so I'll reply to your actual question tonight or tomorrow.

I just wanted to let you know that I am in the process integrating graphiql UI into the demo project - not sure if I have pushed that code yet.

And the schema explorer will fail as we don't implement all the introspection features yet. It does allow you to run queries etc.


________________________________

**Comment by lukemurray** [comment]
@JTravis76 if you are just using `SchemaBuilder.FromObject<DbContext>()` then as mentioned in the Readme the only field arguments that are created are `Id` if the entity has an `Id` property.

If you want to have different (or more) arguments to a graphql field you need to define it. Here is an example
```c#
var schema = SchemaBuilder.FromObject<DbContext>();
schemaProvider.ReplaceField("Group",
                new {
                    groupId = ArgumentHelper.Required<int>(),
                },
                (db, p) => db.Groups.FirstOrDefault(p.groupId),
                "Description of your field", "Group");
```

How are you defining keys on your entities? If you're using some standard Attributes we could update `FromObject<>()` to build arguments based on those attributes. But `FromObject<>()` is mainly meant to a helper to get up and running.

**Comment by JTravis76** [comment]
@lukemurray  Sorry for the delay on this. Got caught down a rabbit hole on another project.

The solution seems odd at first since the default Id work, but after reviewing the document and playing with some examples. This makes perfect sense. Nice work!

Also, was able to get the composite key to work. I was missing the fluent api setting for the context. (newbee to EF Core) Usually, prefer data annotations instead.

I'll leave you to the Introspection Query, that thing is a beast. Will attempt to build a schema.js to side-load the GUI via GraphiQL schema property.

**Comment by lukemurray** [comment]
Note they can get complex if you want multiple, optional arguments to the graphql field. I.e. lets assume you have both `Id` and `GroupId` on that entity. And wanted to support _either_ as an argument. You create the field like so

```c#
schemaProvider.ReplaceField("Group",
                new {
                    groupId = (int?)null, // optional, default to null,
                    id = (int?)null, // optional, default to null
                },
                (db, p) => id.HasValue ? 
                    db.Groups.FirstOrDefault(g => g.Id == p.id) : 
                    groupId.HasValue ? 
                        db.Groups.FirstOrDefault(g => g.GroupId == p.groupId) : 
                        throw new ArgumentException("Please supply groupId or id argument to the Group field"),
                "Description of your field", "Group");
```

You can build pretty complex expressions. I used to support a similar thing like method overload where you could seperately define 2 fields, same name, different arguments. But technically graphql spec deosn't support that. Prehaps I could have the API for that and behind the scene stitch it together.

I'll close this specific issue now, but let me know if you have any other questions or thoughts.
