### ISSUE TITLE
mutation expressions

### ISSUE THREAD

**Issue by rkotenko** [lukemurray/EntityGraphQL#26]
According to the Readme, to have a full graph, we should return an Expression:

```csharp
https://github.com/lukemurray/EntityGraphQL/issues
```

I have my mutation defined like this:

```csharp
public Expression<Func<FlowAppContext, Item>> AddItem(FlowAppContext db, ItemInput newItem)
{
    var item = service.AddItem(newItem);
    service.Save();

    return ctx => ctx.Items.FirstOrDefault(i => i.id == item.id);
 }       
```

When I try to run the mutation though, an error comes back:

```
{
  "errors": [
    {
      "Message": "Object of type 'System.Linq.Expressions.Expression`1[System.Func`2[FlowApp.Models.FlowAppContext,FlowApp.Models.Item]]' cannot be converted to type 'FlowApp.Models.Item'."
    }
  ],
  "data": {}
}
```

I debugged it and found that in ```GraphQLMutationNode.cs```  on line 41, it does not pass the check to see if it is a ```LamdaExpression```.  The type, instead, is ```Expression``` so it tries to just return the results.

The demo looks to have the same signature structure as what I have above.  Not sure what I am doing wrong. Would appreciate any help.

**Comment by rkotenko** [comment]
Looked into it a bit more.  The check is this:

```csharp
if (result.GetType().GetTypeInfo().BaseType.GetTypeInfo().BaseType == typeof(LambdaExpression))
```

but LamdaExpression is the first base type:

``` csharp
if (result.GetType().GetTypeInfo().BaseType
```

while the second base type is ```System.Linq.Expressions.Expression```

**Comment by lukemurray** [comment]
Interesting. What version of dotnet are you running?

**Comment by lukemurray** [comment]
@rkotenko PR #29 has a change to this line that should be more generic. Would be good to know if it resolves your issue

**Comment by lukemurray** [comment]
I reproduced this with botnet 3.x and latest versions have a fix.
