### ISSUE TITLE
Error on EF Core 3 / 3.1

### ISSUE THREAD

**Issue by CrahunGit** [lukemurray/EntityGraphQL#32]
While constructing schema you need to remove type DbContextId in order to graphiql can work.
You can acomplish this with the following code:

demoSchema.RemoveTypeAndAllFields("DbContextId");

This just happens in EF Core 3.0 or above.

**Comment by Peter-Optiway** [comment]
I managed to get it working without doing this.

**Comment by lukemurray** [comment]
Yes this was fixed in 0.32.1
