### ISSUE TITLE
Properties not showing up

### ISSUE THREAD

**Issue by Fireprufe15** [lukemurray/EntityGraphQL#33]
I'm not exactly sure what I'm doing wrong, but following the example, when I make a query for properties, it will return an empty {} for every property I added to the DB, but it doesn't actually print the name or so in the {} that it returns for that object.

For example, if I had 3 propertyTypes in my DB, and I make this request
`{ 
  propertyTypes { id name premium } 
}`

it would return
`{
  "errors": [],
  "data": {
    "propertyTypes": [
      {},
      {},
      {}
    ]
  }
}`

As far as I can tell, from inspecting the code, the values are definitely present in the QueryResult object, but for some reason it seems to not serialize properly when returning out of the controller.

**Comment by Fireprufe15** [comment]
It seems like the built in JSON serializer in  .NET Core 3.1+ doesn't support dictionaries very well.
My current solution is installing the Microsoft.AspNetCore.Mvc.NewtonsoftJson nuget package, and adding `services.AddControllers().AddNewtonsoftJson();` to the startup class.

**Comment by lukemurray** [comment]
Yep. Sorry I just got to this. I should add some notes to the readme about this.

________________________________
