### ISSUE TITLE
Custom queries are executed multiple times?

### ISSUE THREAD

**Issue by Peter-Optiway** [lukemurray/EntityGraphQL#36]
When running the demo project and running the following query
```
{
  actorPager(page: 1, pagesize: 10, search: "an")
  {
    people {
      firstName
    }
    total
    pageCount
  }
}
```
The `QueryController.RunDataQuery` method is executed once but the `GraphQLSchema.PaginateActors` is executed multiple times?

**Comment by JTravis76** [comment]
I too ask the same question. Here is a snippet from a discussion we had. Basically, boils down to how the delegate has to be constructed for EF .

```
So, when you add the field to the schema here
schema.AddField("aboutMe",
	(db) => AboutMe(db, schema.User),
	"All things about me",
	nameof(BusinessObjects.Dtos.AboutMe));

obviously adds the field to the schema. Every time you query that field it calls AboutMe(). Now I see it returns a single object, not a IEnumerable, which is valid and fine. 
Lets say you query like this { query { aboutMe { user { name }, roles { name } } } } we build an expression like this

(dbContext) => AboutMe(db, schema.User) == null ? null : new {
user = new { name = AboutMe(db, schema.User).User.Name },
roles = AboutMe(db, schema.User).Roles.Select(r => new { name = r.Name })
}

So when that gets evaluated AboutMe(db, schema.User) gets called 3 times.
I'm looking at other ways to build the expression,   but to hold up - what I think is a big plus - the heavy integration with EF we can't use expression with bodies,   
ie (dbContext) => { var x = AboutMe(db, schema.User); x == null ? null : new { ... } } which would be 1 call to AboutMe(db, schema.User)

if purely working with EF and a DbContext, it's great, as it is all translated into SQL.  When we introduce more services, the code is evaluated in botnet and methods are executed.

Hope this is making sense!

If AboutMe() is being called x times is might not be a (big) issue. 
Also having the db query in the method call I think means it we run each time.

Not the best answer, let me know if something doesn't make sense.
```

> **With that thought, take caution with objects that might randomly disposed with garbage collection**

**Comment by lukemurray** [comment]
To help demo this, here is the lambda expression that is generated for the above query

```c#
(Param_0, Param_1) => IIF((PaginateActors(Param_0, Param_1) == null), null, new 224d44c8-791d-44e8-be6e-88071c2cc19f() {
    people = PaginateActors(Param_0, Param_1).People
        .Select(param_demo.Person => new 7f0ac197-7bf4-400d-8fdd-71feac738e50() {
            firstName = param_demo.Person.FirstName
        }), 
    total = PaginateActors(Param_0, Param_1).Total, 
    pageCount = PaginateActors(Param_0, Param_1).PageCount
})
```

I'm brain storming ways to make this better. 

What I thought the easiest solution of using an `ExpressionBody` type (that would let us generate `var pagedActors = PaginateActors(Param_0, Param_1);` then replace the multiple calls is not supported.

Maybe this has changed in dotnet 3.x. Open to any other ideas.

**Comment by Peter-Optiway** [comment]
Where in the code is this query generated? just interested to see how it works.

**Comment by lukemurray** [comment]
A few core parts. But first make sure you understand Expression trees in dotnet https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/

Then, `GraphQLCompiler` is the main entry point but `GraphQLVisitor` does all the work. Basically we have a lexer visitor (generated by Antlr4) and we override the visit<token_type> methods to implement processing of that token. 

`GraphQLCompiler` returns a result that you can then execute, see `ExecuteQuery` on `GraphQLResultNode`. This means we can cache this compiled query and pass into different parameters to it.

The query is a dotnet Expression tree like I posted above. If you're running that on a EF context then when it executes, the EF LinqProvider comes in and does it's thing. If you're doing it against a plain object in memory then it is just like running that code.

Does that help?

**Comment by lukemurray** [comment]
And specifically that null check is here https://github.com/lukemurray/EntityGraphQL/blob/master/src/EntityGraphQL/Compiler/GraphQLNode.cs#L115

**Comment by Peter-Optiway** [comment]
I have tried to figure things out a few times, buts sadly i have no knowledge about the visitor pattern or Antlr4 for that matter.
I have som basic knowledge about expression trees.

Why can't we generate something like take the result of `PaginateActors(Param_0, Param_1)` as input instead of Param_0 and Param_1?

That would convert the following 
```
(Param_0, Param_1) => IIF((PaginateActors(Param_0, Param_1) == null), null, new 224d44c8-791d-44e8-be6e-88071c2cc19f() {
    people = PaginateActors(Param_0, Param_1).People
        .Select(param_demo.Person => new 7f0ac197-7bf4-400d-8fdd-71feac738e50() {
            firstName = param_demo.Person.FirstName
        }), 
    total = PaginateActors(Param_0, Param_1).Total, 
    pageCount = PaginateActors(Param_0, Param_1).PageCount
})
```
into 
```
(Param_0) => IIF((Param_0 == null), null, new 224d44c8-791d-44e8-be6e-88071c2cc19f() {
    people = Param_0.People
        .Select(param_demo.Person => new 7f0ac197-7bf4-400d-8fdd-71feac738e50() {
            firstName = param_demo.Person.FirstName
        }), 
    total = Param_0.Total, 
    pageCount = Param_0.PageCount
})
```

**Comment by lukemurray** [comment]
@Peter-Optiway this is exactly what I'd like to look at doing!

I haven't given it a good look / think yet. But we should be able to collect the expression when we are creating it in the visitor and replace it with a parameter and later when executing (and we have all the arguments we require) execute those service calls (once) and pass the results in as arguments.

**Comment by lukemurray** [comment]
@Peter-Optiway would love if you could try out master as I just pushed changes that change the behaviour described above. Only catch is I don't want to do it for any field as if the field is only accessing the schema context data this lets ORMs such as EF Core actually do more on in the SQL.

So any field that uses other services is now wrapped. See the updated paging demo and the Changelog file.

**Comment by lukemurray** [comment]
This has now been published.
