### ISSUE TITLE
Is it available for GET Request?

### ISSUE THREAD

**Issue by NepPure** [lukemurray/EntityGraphQL#37]
When receiving an HTTP GET request, the GraphQL query should be specified in the "query" query string. For example, if we wanted to execute the following GraphQL query:
```
{
  me {
    name
  }
}
```
This request could be sent via an HTTP GET like so:

`http://myapi/graphql?query={me{name}}`

https://graphql.org/learn/serving-over-http/#get-request

**Comment by lukemurray** [comment]
Sure, this library doesn't say anything about where you get the query from. It just gives an example from HTTP POST.

Assuming you're using ASP.NET you can add this to you controller (this is also shown in the demo project)

```c#
        [HttpGet]
        public object Get([FromQuery]string query)
        {
            var gql = new QueryRequest { Query = query };
            try
            {
                var data = _schemaProvider.ExecuteQuery(gql, _dbContext, null, null);
                return data;
            }
            catch (Exception)
            {
                return HttpStatusCode.InternalServerError;
            }
        }
```

**Comment by NepPure** [comment]
Thanks!
