### ISSUE TITLE
ArgumentException in Case of Static Properties/Fields

### ISSUE THREAD

**Issue by ab-tools** [lukemurray/EntityGraphQL#42]
Whenever there are static properties of fields inside `DbContext` class `SchemaBuilder.FromObject` throws an exception:

    System.ArgumentException: 'Instance property 'ConnectionString' is not defined for type '###''

E. g. the `EFDesigner` likes to add a static `ConnectionString` property to each `DbContext` like this:

    public static string ConnectionString { get; set; } = @"Name=ConfigModelConnectionString";

Would it make sense to just ignore all static properties and fields in the model class?
Or is there already a way that I missed to have it ignore those?

Thanks in advance for any idea on this
Andreas

**Comment by lukemurray** [comment]
for `SchemaBuilder.FromObject` and the way it is meant to be used, it might make sense to ignore all static properties. It does have a blacklist that it ignores.

Is this error thrown at building time or when trying to execute a query?

**Comment by ab-tools** [comment]
First thanks for your quick reply!

It throws the error when `SchemaBuilder.FromObject` is called.

**Comment by lukemurray** [comment]
This seems right. The library has never supported those static properties/fields so I have ignored them in 0.60.0-beta3 if you want to give that a try. Should be out of beta soon.

**Comment by ab-tools** [comment]
Thanks a lot for this quick fix:
I've just tried it and this works perfectly now! :-)
