### ISSUE TITLE
Best way to rename field?

### ISSUE THREAD

**Issue by AnderssonPeter** [lukemurray/EntityGraphQL#46]
I have a property named `IPAddress`, and its converted to `iPAddress` what is the best way to rename it?

Currently i do the following:
```
schema.Type<Device>().RemoveField(x => x.IPAddress);
schema.Type<Device>().AddField("ipAddress", x => x.IPAddress, "");
```
The downside i have found is that i loose all comments that i have applied using the Description attribute. (Same thing happens with `MACAddress`)

**Comment by JTravis76** [comment]
This is common scenario for me also and a great discussion. 

Was testing this in my forked branch. Allowing developers to change the spelling/casing of either a field and/or its members via the `DisplayNameAttribute`. Much like the `DescriptionAttribute`. This would adjust the name during the schema-first process.

Haven't submitted a PR yet, as I am still testing. But here is a code sample.

```cs
var f = new Field(SchemaGenerator.ToCamelCaseStartsLower(prop.Name), le, description, null, null, requiredClaims);

/*== JT * Allow user to customize the schema-first casing. */ 
string propName = SchemaGenerator.ToCamelCaseStartsLower(prop.Name); 
var n = (DisplayNameAttribute)prop.GetCustomAttribute(typeof(DisplayNameAttribute), false); 
if (n != null) propName = n.DisplayName;
//==

var f = new Field(propName, le, description, null, null, requiredClaims);
```

**Comment by lukemurray** [comment]
Yep, the `FromObject()` helper adopts the common "standard" of GraphQL being `lowerCaseCamel`. Currently the only way to no have that happen is to not use `FromObject` or replace the fields as you are.

100% open to having a `NamingProvider` that we can swap out or write your own.

Also using the `DisplayNameAttribute` makes sense too @JTravis76

**Comment by AnderssonPeter** [comment]
Using the `DisplayNameAttribute` would be nice and consistent with `DisplayNameAttribute`.

I also checked Newtonsoft somehow handles both MACAddress and IPAddress correctly.

**Comment by lukemurray** [comment]
Hi, although it would be nice to support `DisplayNameAttribute` as well I have added a `fieldNamer` func when generating the schema.

See version `0.63.0-beta1`. I'd love to know if you find any issues as a bunch has changed to better hold type information for the schema generation and introspection queries.

To override the default naming and have it purely use the field name you have in C# provide the following func.

```c#
var schema = SchemaBuilder.FromObject<MyContext>(true, true, field => field.Name);
```

**Comment by AnderssonPeter** [comment]
I think i found a bug
https://github.com/lukemurray/EntityGraphQL/blob/74f8d576870eb4cfc31a3a2fc4607bdf058eb513/src/EntityGraphQL/Schema/SchemaBuilder.cs#L46 the `fieldRenamer` is never passed to the other method.

**Comment by lukemurray** [comment]
Whoops thanks.

________________________________

**Comment by AnderssonPeter** [comment]
@lukemurray the `AddMutationFrom` does not have a fieldNamer argument so the input arguments there still get incorrectly renamed.

How about storing the one that gets sent into `FromObject` that way we don't have to send a new one with every `AddType`.

```
"kind": "OBJECT",
"name": "Mutation",
"description": "The mutation type, represents all updates we can make to our data",
"fields": [{
	"name": "addDevice",
	"description": null,
	"args": [{
			"name": "mACAddress", <---
			"description": null,
			"type": {
				"kind": "NON_NULL",
				"name": null,
				"ofType": {
					"kind": "SCALAR",
					"name": "String",
					"ofType": null
				}
			},
			"defaultValue": null
		}, {
			"name": "iPAddress", <---
			"description": null,
			"type": {
				"kind": "NON_NULL",
				"name": null,
				"ofType": {
					"kind": "SCALAR",
					"name": "String",
					"ofType": null
				}
			},
			"defaultValue": null
		}, {

```

Or if you want a function that handles this correctly (I have tested all combinations i can think of but i might have missed something):
```
private static string FieldNamer(MemberInfo memberInfo)
{
    var name = memberInfo.Name;
    for (var i = 0; i < name.Length; i++)
    {
        if (!char.IsUpper(name[i]))
        {
            if (i == 0)
            {
                return name;
            }
            if (i == 1)
            {
                return name.Substring(0, i).ToLower() + name.Substring(i);
            }
            else
            {
                return name.Substring(0, i - 1).ToLower() + name.Substring(i - 1);
            }
        }
    }
    return name.ToLower();
}
```

**Comment by lukemurray** [comment]
fieldNamer is now kept in schemaProvider and used.
