### ISSUE TITLE
Count selected objects by type?

### ISSUE THREAD

**Issue by AnderssonPeter** [lukemurray/EntityGraphQL#48]
Is there some way to after each query get a summary of how many of each .net type it contains (recursively and even if its just partial)?

**Comment by lukemurray** [comment]
Sorry, I'm not sure what you're asking.

If you're asking can you do something like

```gql
query {
  myThings {
    name
    moreThings.count()
  }
}
```

The answer is no that isn't valid GraphQL. The GraphQL way is to expose more fields (might be able to do something with directive but I'm not sure) e.g.

when you build your schema
```c#
schema.Type<MyThing>().AddField("moreThingsCount", myThing => myThing.MoreThings.Count(), "Return the count of MoreThings");
```

Then you can

```gql
query {
  myThings {
    name
    moreThingsCount
  }
}
```

If you're asking something else then can you please give an example of what you're trying to do?

**Comment by AnderssonPeter** [comment]
Sorry if i was unclear.
Lets say i have the following DbContext:
```
public class DatabaseContext : IdentityDbContext
{
    public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options)
    {
    }

    public DbSet<Device> Devices { get; set; }
    public DbSet<DeviceTag> DevicesTags { get; set; }
}

public class Device
{
	public int Id { get; set; }
	public string Name { get; set; }
	public ICollection<DeviceTag> Tags { get; set; }
}

public class DeviceTag
{
	public int DeviceId { get; set; }
	public Device Device { get; set; }
	public string Value { get; set; }
}
```
And then execute 
```
query {
  devices {
    name
    tags {
     value
    }
  }
}
```
And get the following result:
```
{
  "errors": [],
  "data": {
    devices: [
      {
        "name": "test",
        "tags": [
          { "value": "1" },
          { "value": "2" }
        ]
      }
    ]
  }
}
```

The summary would then be 
```
Device: 1
DeviceTag: 2
```

The only way i found was to parse the resulting json and figure it out that way, but i just want to know if there is any easier way?

**Comment by lukemurray** [comment]
If you want an easy way to count the total number of devices and tags I would do what I said above. example in the terms you used

```c#
// add root level fields
schema.AddField("deviceCount", db => db.Devices.Count(), "Return the count of Devices");
schema.AddField("tagCount", db => db.DeviceTags.Count(), "Return the count of DeviceTags");

// or if you want the count on the Devices (not all tags in the DB)
schema.Type<Device>().AddField("tagCount", d => d.Tags.Count(), "Return the count of DeviceTags");
```
then
```gql
{
    deviceCount
    tagCount

    # or count tags per device
    devices {
        tagCount
    }
}
```

If it is something else I don't think I can help.

This library focuses on letting you build a GraphQL API, how you consume it on the other side (the client making the calls) is unrelated to this library. Typically you are reading the result into classes (usually with a library too like deserialise the JSON into objects with JSON.NET) and using the data how you wish.

**Comment by AnderssonPeter** [comment]
Thanks for your response, i want to do this on the server without the client noticing.
The idea here is that we could debit our customers based on what they access in our api.
So if we could count what they access we could say Devices have a 1$ price and Tags cost 0.25$

**Comment by lukemurray** [comment]
Got it.

Not really a goal for this library so I will close the issue.

But thinking about it...

you want both to know the types they queried and how many objects are returned. That's going to be tricky as when you have the results it is all anonymous objects or on the other end JSON.If you know your data model you know that a list of tags is of type DeviceTag so you could map it that way.

Sorry I don't have much for you. And it isn't a goal of this library.

**Comment by AnderssonPeter** [comment]
Thanks for the idea, i get that this is not a goal.
