### ISSUE TITLE
How to filter using DateTime?

### ISSUE THREAD

**Issue by ibraheemalkilanny** [lukemurray/EntityGraphQL#49]
No docs! Where is docs?

Why the following not working?

```
query {
    auditLogs(type: 3) {
        oldValues newValues type affectedTableName affectedRecordKey 
        time
    }
}
```

Also how to paging? sorting? if not implemented using client side graphql, this lib wasted our time 2 weeks

**Comment by lukemurray** [comment]
This library doesn't solve everything for you. If you see no value in it, move on.

There are no fancy docs, the API is pretty small, the readme covers most of it. There is a [tiny example of paging on a field in the readme](https://github.com/lukemurray/EntityGraphQL#paging) also the demo has an [example of paging more based on how others do it by adding a paging object](https://github.com/lukemurray/EntityGraphQL/blob/master/src/demo/GraphQLSchema.cs#L44)

Which way suits you best is up to you and your application.

Regarding your error, I can't do anything with your query. Can you provide the error you are getting, what your schema looks like, anything that would actually help figure out what is going wrong?

As for the title of the issue, filtering is up to you to implement how it fits your application. Given a schema with a type `MyRecord` that has a `Created` field on it as a `DateTime` type you can replace the generated field with one with an argument (note the `FromObject` is just a helper).

```c#
var schema = SchemaBuilder.FromObject<MyDbContext>();
//...
// below we add a field with an argument, the argument defaults to null and is not required
schema.ReplaceField("myRecords", new { createdAfter = (DateTime?)null }, (db, args) => db.MyRecords.WhereWhen(r => r.Created >= args.createdAfter.Value, p.createdAfter.HasValue), "My description");
```

Now you can query
```gql
query All {
    myRecords { created ... }
}

query Filtered {
    myRecords(createdAfter: "2020-01-01") { created ... }
}
```

**Comment by lukemurray** [comment]
Closing as I have no information on the problem query. Reopen with more information if still an issue.
