### ISSUE TITLE
Add support for GraphQL directives

### ISSUE THREAD

**Issue by lukemurray** [lukemurray/EntityGraphQL#5]
See https://graphql.org/learn/queries/#directives

**Comment by lukemurray** [comment]
currently in 0.60.0-beta1.
- skip and include done, can add your own to change expression pre-execution.

**Comment by JTravis76** [comment]
Just curious, where can you apply directives? Main field and/or its members??

```
query {
    movies @include(if: Boolean) {
        name @skip(if: Boolean)
    }
}
```

**Comment by lukemurray** [comment]
Should work on both. Let me know if you’re having issues

________________________________
