### ISSUE TITLE
Execute mutation without paramters?

### ISSUE THREAD

**Issue by AnderssonPeter** [lukemurray/EntityGraphQL#53]
I have a mutation without any parameters seems impossible to execute? (most likely its my GraphQL knowledge is lacking)

The following yields `Missing bracets for mutation call scanForDevices`.
```
mutation test {
  scanForDevices {
    id
  }
}
```

The following yields `Error: line 2:17 extraneous input ')' expecting {1..11, 49}`.
```
mutation test {
  scanForDevices() {
    id
  }
}
```

I have tried both with a empty parameter/arguments class and with no parameter/arguments class at all.

Method:
```
[GraphQLMutation]
public async Task<Expression<Func<DatabaseContext, IQueryable<Device>>>> ScanForDevices(DatabaseContext databaseContext, Empty parameters, IJobManager jobManager)
{
	var ids = await jobManager.StartWaitAsync<IEnumerable<int>, IDetectDeviceCommand>(ddc => ddc.ScanAsync()).ConfigureAwait(false);
	return ctx => ctx.Devices.Where(x => ids.Contains(x.Id));
}
```

**Comment by lukemurray** [comment]
A little I still need to clean up but master has some changes for this, but it introduces a breaking change.

Mutation methods no longer follow a strict order of parameters and you can include only what you require. Be that none or 1 or many. The breaking change for this is that the class that does represent the mutation arguments needs to implement the `IMutationArguments` interface.

Yours would look like this

```gql
mutation test {
  scanForDevices() {
    id
  }
}
```

```c#
[GraphQLMutation]
public async Task<Expression<Func<DatabaseContext, IQueryable<Device>>>> ScanForDevices(IJobManager jobManager)
{
	var ids = await jobManager.StartWaitAsync<IEnumerable<int>, IDetectDeviceCommand>(ddc => ddc.ScanAsync()).ConfigureAwait(false);
	return ctx => ctx.Devices.Where(x => ids.Contains(x.Id));
}
```

**Comment by lukemurray** [comment]
This is now in `0.63.0-beta1` on nuget. I'd love to know if you find any issues before I take it out of beta as a bunch has changed - see [changelog](https://github.com/lukemurray/EntityGraphQL/blob/master/CHANGELOG.md#0630)

**Comment by AnderssonPeter** [comment]
@lukemurray i will check it out this evening! thanks for your fast fixes!

**Comment by AnderssonPeter** [comment]
The one thing i might change is to use a attribute instead of `IMutationArguments`, but that's just a preference.
You could even allow for the attribute to be set on the parameter or class for added flexibility.
```
public async Task<Empty> DeleteSensor(DatabaseContext databaseContext, [MutationArguments] DeleteSensorParameters model)
                                                                       ^^^^
```

**Comment by lukemurray** [comment]
Yeh that dies make more sense. We use attributes else where

________________________________

**Comment by lukemurray** [comment]
There is a `beta2` with the attribute. Will make non beta in a few days

**Comment by AnderssonPeter** [comment]
After trying out the schema generated with https://graphql-code-generator.com/#live-demo it seems they don't like mutations with () and no parameters.
So `scanForDevices(): [Device!]` does not validate but `scanForDevices: [Device!]` does.

**Comment by lukemurray** [comment]
Sorry can you expand on that. You are saying this library should support both a mutation query with `scanForDevices()` or that the schema this library generates should be `scanForDevices(): [Device!]` not `scanForDevices: [Device!]`?

**Comment by AnderssonPeter** [comment]
I'm no GraphQL expert, so take what i write with a pinch of salt!

The utility at https://graphql-code-generator.com/#live-demo does not seem to like `()` without parameters
Try to enter:
```
schema {
  query: Query
}

type Query {
  user(): User <--- Error
}

type User {
  id: ID!
}
```

Then change `user(): User` into `user: User` and it validates without errors!

**Comment by lukemurray** [comment]
I follow, this repo generates it with `()`. I don't think it should. The spec isn't really clear. GraphiQL does process either. going with no brackets.
