### ISSUE TITLE
See issue#16156

### ISSUE THREAD

**Issue by dani3lod** [lukemurray/EntityGraphQL#55]
i want paging by Status, the query: {mydb( Take:100, Skip:1, Status:"dfgd" ) { id }}

the results:

{
    "errors": [
        {
            "message": "See issue#16156"
        }
    ],
    "data": {}
}

which is the issue ?

**Comment by lukemurray** [comment]
Can you show me the field definition please?

________________________________

**Comment by dani3lod** [comment]
i fixed it

**Comment by lukemurray** [comment]
What was the issue?

________________________________
