### ISSUE TITLE
GraphQL Query string to LINQ Expression

### ISSUE THREAD

**Issue by MelbourneDeveloper** [lukemurray/EntityGraphQL#59]
Hi,

This library looks awesome. Apologies in advance if I've missed something here. I've spent some time looking through the examples on the front page but wasn't sure how to do this. What I'm looking for is a way to retrieve a LINQ Expression from a GraphQL string query. This would be totally decoupled from EF or even IQueryable. 

The delegate would look exactly like this:

```cs
delegate Expression GetExpression(string graphQl);
```

Or potentially this with generics:

```cs
delegate Expression<Func<T, bool>> GetExpression<T>(string graphQl);
```

Is there a straight forward way to implement this delegate with this library?

Christian

**Comment by MelbourneDeveloper** [comment]
Just some notes. On the face of it [`ISchemaProvider`](https://github.com/lukemurray/EntityGraphQL/blob/5c6e09a89d9ce9228a0fa35fb03d690e4d6f167a/src/EntityGraphQL/Schema/ISchemaProvider.cs#L21) looks like a nice abstraction. However, it takes a Type [here](https://github.com/lukemurray/EntityGraphQL/blob/5c6e09a89d9ce9228a0fa35fb03d690e4d6f167a/src/EntityGraphQL/Schema/ISchemaProvider.cs#L21). That type is used by [`SchemaBuilder`](https://github.com/lukemurray/EntityGraphQL/blob/5c6e09a89d9ce9228a0fa35fb03d690e4d6f167a/src/EntityGraphQL/Schema/SchemaBuilder.cs#L120) to extra fields from a Type.

Would I be right in thinking that this type would need to be an Entity Framework style `DbContext`? I.e. follow a pattern where the `DbContext` provides a set of `DbSet<T>` properties? Is there a way to build a schema from scratch without tying it to an EF style `DbContext`?

**Comment by MelbourneDeveloper** [comment]
This works:

```cs
public Expression<Func<T, bool>> GetExpression<T>(string graphQl)
{
    var compiledQueryResult = EntityQueryCompiler.Compile(graphQl, SchemaBuilder.FromObject<TestSchema>(), null, new DefaultMethodProvider(), null);
    var expressionResult = compiledQueryResult.ExpressionResult;
    var whereMethodExpression = (dynamic)expressionResult.Expression;
    return (Expression<Func<T, bool>>)whereMethodExpression.Arguments[1];
}
```

**Comment by MelbourneDeveloper** [comment]
Now, I've got this which is great:

```cs
public class ExpressionFromGraphQLProvider
{
    ISchemaProvider _schemaProvider;

    public ExpressionFromGraphQLProvider(ISchemaProvider schemaProvider)
    {
        _schemaProvider = schemaProvider;
    }

    public Expression GetExpression(string graphQl)
    {
        var compiledQueryResult = EntityQueryCompiler.Compile(graphQl, _schemaProvider, null, new DefaultMethodProvider(), null);
        var expressionResult = compiledQueryResult.ExpressionResult;
        var whereMethodExpression = (dynamic)expressionResult.Expression;

        var secondArgument = whereMethodExpression.Arguments[1];

        //This is DB Context classes
        return (Expression)secondArgument.Operand;
    }
}
```

This is where I try to use the expression for two different data layers. EF and RepoDb:

```cs
[TestMethod]
public async Task TestGetExpressionWithEFCoreAndRepoDb()
{
    var name = "Christian";

    var expressionFromGraphQLProvider = new ExpressionFromGraphQLProvider(SchemaBuilder.FromObject<PeopleDbContext>());

    var expression = expressionFromGraphQLProvider.GetExpression($@"person.where(name = ""{name}"")");

    SqLiteBootstrap.Initialize();

    using (var peopleDbContext = new PeopleDbContext())
    {
        peopleDbContext.Person.RemoveRange(await peopleDbContext.Person.ToListAsync());

        var key = Guid.NewGuid().ToString();
        peopleDbContext.Person.Add(new Person { Id = key, Name = name });
        peopleDbContext.Person.Add(new Person { Id = Guid.NewGuid().ToString(), Name = "123" });
        await peopleDbContext.SaveChangesAsync();


        var people = await peopleDbContext.Person.Where((Expression<Func<Person, bool>>)expression).ToListAsync();

        Assert.AreEqual(1, people.Count);
    }

    using (var connection = new SQLiteConnection(PeopleDbContext.ConnectionString))
    {
        var people = connection.Query<Person>(expression).ToList();
        Assert.AreEqual(1, people.Count);
    }
}
```

This is the exception I get with Repo Db:

![image](https://user-images.githubusercontent.com/16697547/88368769-0fcada00-cdd2-11ea-97a1-1acb7faeb5e7.png)

**Comment by MelbourneDeveloper** [comment]
This expression works on both data layers though:

```cs
Expression<Func<Person, bool>> expression = (p) => p.Name == name;
```

**Comment by MelbourneDeveloper** [comment]
@lukemurray any thoughts?

**Comment by lukemurray** [comment]
hey @MelbourneDeveloper , just looking at this now.

First you do not need to use `DbContext` you could build a schema from scratch from `object` type of a custom type like it looks like you have done. This library just builds LINQ expressions against an object structure. If that happens to be a `DbContext` then you get those benefits.

So you are building a schema from `PeopleDbContext` can you post that too?

When you compile `person.where(name = ""{name}"")` against `PeopleDbContext` it will look for a property/field called `person`.

Also `person.where(name = ""{name}"")` is not valid GraphQL, but you are using `EntityQueryCompiler` which allows this so that's good, just wanted to spell that out though.

EntityQueryCompiler by itself is, well, less tested.

You should be able to take the `compiledQueryResult.LambdaExpression` which should be an expression like `(Person p) => p.Where(t => t.Name == "...")`

Note that perhaps you mean `people.where()`? But that depends on how you defined the schema or the `PeopleDbContext` class.

If you can provide a sample project I'd happily have a quick look.

**Comment by MelbourneDeveloper** [comment]
@lukemurray 

> First you do not need to use DbContext you could build a schema from scratch from object type of a custom type like it looks like you have done.

Thanks. you're right. This works, and this is how I would do it so as to avoid EF specifics:

```cs
var schema = SchemaBuilder.FromObject<object>();
schema.AddType<Person>("A Person");
```

or this:

```
var schema = SchemaBuilder.Create<object>();
schema.AddType<Person>("A Person");
```

I will be providing a sample soon. This is part of a larger project that I will be open-sourcing soon.

**Comment by MelbourneDeveloper** [comment]
The left over issue is that Repo Db doesn't accept the same expression that EF does. I need to do some investigation to determine if that is because the expression has a problem, or if Repo Db is just interpreting the expression wrong.

**Comment by MelbourneDeveloper** [comment]
Take a look at this @lukemurray .

It works well with [Entity Framework](https://github.com/MelbourneDeveloper/Samples/blob/82b63d6f0058e9eda6bd0c5374887935fb3b352a/BusinessAndDataLayers/BusinessAndDataLayers/UnitTest1.cs#L57), [LiteDB (No SQL)](https://github.com/MelbourneDeveloper/Samples/blob/82b63d6f0058e9eda6bd0c5374887935fb3b352a/BusinessAndDataLayers/BusinessAndDataLayers/UnitTest1.cs#L78) but it fails with [Repo DB](https://github.com/MelbourneDeveloper/Samples/blob/82b63d6f0058e9eda6bd0c5374887935fb3b352a/BusinessAndDataLayers/BusinessAndDataLayers/UnitTest1.cs#L102).

It's epecially awesome that it works with LiteDB

**Comment by lukemurray** [comment]
@MelbourneDeveloper I couldn't get it to debug in VS Code. Did you have the error it gets? Or any more information?

**Comment by lukemurray** [comment]
@MelbourneDeveloper just wondering if there is still something you'd like a hand with here?

**Comment by MelbourneDeveloper** [comment]
@lukemurray let's close this for now. I've done lots of refactors in the area. I will ping you when I back to it and we can reopen it again.

**Comment by lukemurray** [comment]
sure thing.
