### ISSUE TITLE
Running Mutation returns: "Unable to cast object of type 'EntityGraphQL.Compiler.GraphQLMutationNode' to type 'EntityGraphQL.Compiler.GraphQLQueryNode'."

### ISSUE THREAD

**Issue by nahro1001** [lukemurray/EntityGraphQL#60]
Hi,

 I am currently getting familiar with GraphQL in general - and used EntityGraphQL to get the hang of it and evaluate it for projects.
So this might not be an actual issue but me misunderstanding something fundamentally.

I followed the Readme for Mutations and implemented the 

```
public class TestTableMutation
    {
        [GraphQLMutation("Add new TestTable Entry")]
        public Expression<Func<TestDbContext, TestTable>> AddTestTableViaMutation(TestDbContext context, TestTableArgs args)
        {
            TestTable newTable = new TestTable();
            newTable.Age = args.Age;
            newTable.Name = args.Name;
            newTable.Id = context.TestTable.Count();
            
            context.TestTable.Add(newTable);
            context.SaveChanges();
            
             return context => context.TestTable.First();
        }
    }

    [MutationArguments]
    public class TestTableArgs
    {
        public string Name;
        public int Age;
    }
```

Added the Mutation to the schema:

```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers().AddNewtonsoftJson();
            services.AddScoped<IInterProcessService, ServiceHandler>();
            services.AddDbContext<TestDbContext>();

            var schema = SchemaBuilder.FromObject<TestDbContext>(false,true);
            schema.AddMutationFrom(new TestTableMutation());
                    
            services.AddSingleton(schema);
        }
```

Yet when I run the query:
```
 {
     addTestTableViaMutation(name: "Stan", age:33)
 }
```

All I get is the following response:
```
{
    "errors": [
        {
            "message": "Unable to cast object of type 'EntityGraphQL.Compiler.GraphQLMutationNode' to type 'EntityGraphQL.Compiler.GraphQLQueryNode'."
        }
    ],
    "data": {}
}
```

tinkered with it for a couple days now and couldn't get it to run.  Not sure what I am missing really.

**Comment by nahro1001** [comment]
Ok I realised my mutation Query is absolutely wrong. But even following other Guides and the GraphQL Docu I would have assumed that my mutation query should look like this:
```
 mutation {
        addTestTableViaMutation(name: "Stan", age:33){
             id name
         }
    }  
```

which does not work, but this one does:

```
 mutation addTestTableViaMutation {
        addTestTableViaMutation(name: "Stan", age:33){
             id name
         }
    }  
```
I just dont get quite why. But that is none of your concern - if someone feels like answering would help a lot.

**Comment by lukemurray** [comment]
Was just replying to this. Yes the first query was incorrect.

The second query... I swear GraphQL spec said an `OperationName` was required for mutations. But from https://graphql.org/learn/queries/#operation-name
>The operation name is a meaningful and explicit name for your operation. It is only required in multi-operation documents

So this is a bug. Thanks. I'll update that so you can have unnamed mutations if it's the only operation.
