### ISSUE TITLE
Pass an array in the query's argument

### ISSUE THREAD

**Issue by c4bo3l** [lukemurray/EntityGraphQL#63]
Hi,
I got this error message when trying to pass an array in the argument.
`"Error: line 2:21 no viable alternative at input '['"`

Example query:
`{
  tables (findIds: ["Id1", "Id2"]) {
    id,
    name
  }
}`

In the schema, I could see the information is generated correctly.
`tables (findIds: [String]): ReturnType`

In the customization, I put this code.
`schemaProvider.AddField(tables, new { findIds = (string[]) null }, (db, p) => Process(db, p), "Some description", "ReturnType")`

Is there something that I missed?

Thanks in advance.

P.S. I'm using ASP.Net Core 3.1 and EntityGraphQL 0.64.0

**Comment by JTravis76** [comment]
Hi, believe it is recommended to use variables when passing complex objects or arrays. Try something like this. 

```
query Op1($p1:[String]) { 
  tables (findIds: $p1) { id, name } 
}
```
Variables 
```
{ "p1" : ["Id1", "Id2"] }
```

**Comment by c4bo3l** [comment]
@JTravis76 ,
It works. Thanks.
