### ISSUE TITLE
Authorization for types using the schema object

### ISSUE THREAD

**Issue by AradAral** [lukemurray/EntityGraphQL#65]
Currently, we can configure authorization for both fields and types using the `[GraphQLAuthorize]` attribute:
For types, we can set the `[GraphQLAuthorize]` attribute on the `DbSet<>` properties in our context class (if we're using EF of course):
```
[GraphQLAuthorize("super-admin")]
public DbSet<Purchase> Purchases{ get; set; }
```
For fields, we can set the `[GraphQLAuthorize]` attribute on the properties of our entity classes. Simple:
```
[GraphQLAuthorize("super-admin")]
public string Email { get; set; }
```

However, when it comes to configuring authorization using the schema object, it's currently only possible for fields:
```
schemaProvider.Type<User>().GetField("email").RequiresAllClaims("super-admin");
```
I can't do something like this, and I think it's reasonable to say it should be possible:
```
schemaProvider.Type<Purchase>().RequiresAllClaims("super-admin");
```

**Comment by lukemurray** [comment]
Thanks, makes sense to allow that. I'll have look when I next get some time to work on this :)

**Comment by lukemurray** [comment]
added to 0.65

**Comment by AradAral** [comment]
Sounds great. Thank you!

**Comment by AradAral** [comment]
Sounds good. Thank you.
